### ISSUE TITLE
Yahoo! answers dataset

### ISSUE THREAD

**Issue by hsannn** [HenryPengZou/JointMatch#1]
Hello,

I want to reproduce your excellent work.
However, it seems that you haven't publicly released the Yahoo! dataset you used.
While I could reproduce it using the Yahoo! dataset myself, 
I would like to use the one prepared by you for more accurate experimental results. 

Is it possible to have an update on GitHub?

**Comment by HenryPengZou** [comment]
Hi there, the Yahoo dataset I used in this paper can be downloaded here:[Yahoo!  Dataset](https://github.com/HenryPengZou/DeCrisisMB/tree/main/data/yahoo); I will also update in the data folder soon~

**Comment by HenryPengZou** [comment]
Hi @hsannn, Yahoo! Dataset is also updated in our data folder: https://github.com/HenryPengZou/JointMatch/tree/main/data

Feel free to let me know if you have any other questions~
