### ISSUE TITLE
indices error

### ISSUE THREAD

**Issue by PandaA0520** [HenryPengZou/JointMatch#3]
hello，

I encountered an error while reproducing the code. I used the first 100 entries of ag_news as test samples, and then ran it on my laptop. There were no issues during initialization, but an error occurred during the first iteration.It seems to be because the data is not on the same area (CPU or GPU). Could you help me solve this problem? Thank you very much. Below is the specific error message.
---------------------------------------
data_path:  ../data/ag_news

There are 1 GPU(s) available.
We will use the GPU- 0 NVIDIA GeForce RTX 3070 Laptop GPU
n_labeled_per_class:  5
train_df samples: 100
train_labeled_df samples: 20
train_unlabeled_df samples: 80
Check n_smaples_per_class in the original training set:  {2: 37, 3: 26, 0: 19, 1: 18}
Check n_smaples_per_class in the labeled training set:  {2: 5, 1: 5, 3: 5, 0: 5}
Check n_smaples_per_class in the unlabeled training set:  {2: 32, 3: 21, 0: 14, 1: 13}
n_classes:  4
net_arch:  bert-base-chinese lr:  1e-05
net_arch:  bert-base-chinese lr:  1e-05
>>Epoch 0 Step 0 acc_val 0.260000 f1_val 0.104000 acc_train 0.200000 f1_train 0.083333 psl_cor 0 psl_totl 0 pslt_global 0.000000 Tim 0:02:11
cw_psl_eval:  [0, 0, 0, 0] [0, 0, 0, 0]
psl_acc: None cw_psl_acc:  [nan, nan, nan, nan]
Save model to ./experiment/ag_news/output/

Traceback (most recent call last):
  File "E:\JM\code\panel_main.py", line 34, in <module>
    multiRun(device_idx=device_idx, experiment_home=experiment_home, dataset=dataset, num_runs=num_runs,
  File "E:\JM\code\main.py", line 523, in multiRun
    result = oneRun(log_dir, output_dir_experiment, **params, seed=seeds_list[i])             
  File "E:\JM\code\main.py", line 382, in oneRun
    gt_labels_u = batch_unlabel['label'][u_psl_mask].to(device)
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Process finished with exit code 1

**Comment by HenryPengZou** [comment]
Hi @PandaA0520, this problem occurs because you're trying to use tensor indices from a different device (like a GPU) than the tensor you're trying to index into, which in this case is on the CPU. You can move 'batch_unlabel['label']' and 'u_psl_mask' to the same device to solve this issue. Here is an example:


```Python
    # Check & set device
    if torch.cuda.is_available():     
        device = torch.device("cuda", device_idx)
        print('\nThere are %d GPU(s) available.' % torch.cuda.device_count())
        print('We will use the GPU-', device_idx, torch.cuda.get_device_name(device_idx))
    else:
        print('\nNo GPU available, using the CPU instead.')
        device = torch.device("cpu")
```

You can choose to move 'batch_unlabel['label']' to GPU: (Recommended)
```Python
batch_unlabel['label'] = batch_unlabel['label'].to(device) # assume 'device' is a GPU device
# u_psl_mask = u_psl_mask.to(device) # you can add this line to make sure 'u_psl_mask' is also on GPU
```


Or you can choose to move 'u_psl_mask' to CPU:

```Python
u_psl_mask = u_psl_mask.to('cpu') 
# batch_unlabel['label'] = batch_unlabel['label'].to('cpu') # you can add this line to make sure 'batch_unlabel['label']' is also on 'cpu'
```
